name: stellar-sdk
version: '0.2.0.0'
github: "teequoo/stellar-sdk"
license: Apache-2.0
author: "teequoo"
maintainer: "teequoo"
synopsis: A library to use as SDK for the Stellar payment network.
description: This library provides functions to interact with the Stellar payment network via a Horizon server. It support querying the network, as well as building, signing and submitting transactions.
category: API

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

language: GHC2021
ghc-options: -Wall

library:
  dependencies:
  - aeson
  - base
  - base32
  - base64-bytestring
  - bytestring
  - Cabal
  - cereal
  - containers
  - crypton
  - ed25519
  - filepath
  - haskell-src-exts
  - parsec
  - req
  - SHA
  - text
  - vector
  source-dirs: library

tests:
  stellar-sdk-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - bytestring
    - hspec
    - HUnit
    - stellar-sdk
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
